version: '3.1'

services:
  postgres:
      image: postgres
      container_name: remarkably_db
      environment:
        POSTGRES_DB: remarkably_db
        POSTGRES_PASSWORD: password
      volumes:
        - remarkably_postgresdbdata:/var/lib/postgresql/data
      ports:
        - "5431:5432"
      restart: always
      networks:
        - default

  remarkably_api:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: remarkably_api
      ports:
        - "5000:5000"
      volumes:
        - .:/app
      depends_on:
        - postgres
      restart: always
      networks:
        - default

volumes:
  remarkably_postgresdbdata: