"""Initial migration.

Revision ID: 917bb7b038e6
Revises: 
Create Date: 2020-08-18 13:43:37.816585

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '917bb7b038e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    connection = op.get_bind()

    result = connection.execute("""

                       create EXTENSION if not EXISTS "uuid-ossp";

                       """)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moveout',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('item', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('detail', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('SYSTEM', 'EXTERNAL', 'STAFF', 'USER', 'UNKNOWN', name='eventtype'), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item'], ['moveout.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # insert seed data
    from db import insert_seed_data
    insert_seed_data(connection)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    op.drop_table('moveout')
    op.execute('DROP TYPE ' + 'eventtype')
    # ### end Alembic commands ###
