"""Initial migration.

Revision ID: e58d96199aa9
Revises: 
Create Date: 2020-08-15 14:52:00.245050

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e58d96199aa9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    connection = op.get_bind()

    result = connection.execute("""

                       create EXTENSION if not EXISTS "uuid-ossp";

                       """)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
                    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'),
                              nullable=False),
                    sa.Column('detail', sa.String(length=200), nullable=False),
                    sa.Column('type', sa.Enum('SYSTEM', 'EXTERNAL', 'STAFF', 'USER', 'UNKNOWN', name='eventtype'),
                              nullable=False),
                    sa.Column('created_date', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    # ### end Alembic commands ###
